destination: ./_site
auto:        true
#lsi:         false
server_port: 4000
#pygments:    true
#markdown:    rdiscount
#permalink:   /:categories/:year:month:day-:title.html
#permalink:   /:year:month:day-:title/
exclude: Gemfile, Gemfile.lock, bundle, README.md, log
